name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  biome-check:
    name: Lint check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.15.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run lint
